Convert relative URLs to absolute in git READMEs
apify/apify-shared-js pull request #81
Opened 2020-10-27 13:15 UTC by mhamas

2020-10-29 12:51 UTC, mtrunkat requested changes

2020-10-29 12:51 UTC, mtrunkat commented on src/git.js
> +import GitUrlParse from 'git-url-parse';
This should be lowercased as it's a function now constructor

2020-10-29 12:51 UTC, mtrunkat commented on src/git.js
> +    // Images in markdown have syntax ![alt text](image url)
There could be also includes as HTML (for example when embedded in HTML table) - `<img src=... />`

2020-10-30 13:50 UTC, mhamas commented
@mtrunkat I've addressed the comments and verified locally that this works fine.

2020-11-02 16:51 UTC, gippy approved these changes

2020-11-03 14:18 UTC, mtrunkat approved these changes

2020-11-03 15:05 UTC, merged